# Generated by Django 3.1.12 on 2025-06-27 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corredores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nota', models.TextField(blank=True)),
                ('distancia', models.FloatField()),
                ('coordenadas', models.JSONField()),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
