# Generated by Django 3.1.12 on 2025-05-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corredores', '0002_registros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarioinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apodo', models.CharField(max_length=20)),
                ('edad', models.CharField(max_length=3)),
                ('descripcion', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes_usuarios/')),
            ],
        ),
        migrations.AddField(
            model_name='registros',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='registros',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
