# Generated by Django 3.1.12 on 2025-07-04 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corredores', '0003_mensajechat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ruta',
            old_name='creada_en',
            new_name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='ruta',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='corredores.registros'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ruta',
            name='distancia',
            field=models.FloatField(default=0),
        ),
    ]
